version: '3.0'

services:
  app-server:
    container_name: springboot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - '8080:8080'
  
# Names our volume
volumes:
  my-db:
