version: '3.0'

services:
  db:
    container_name: mysql
    image: mysql
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    environment:
      MYSQL_USER: 'tuan'
      # You can use whatever password you like
      MYSQL_PASSWORD: '123456'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123456'
    volumes:
      - my-db:/var/lib/mysql
  webapp:
    container_name: springboot-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
    - db
    ports:
    - '8080:8080'
  # reverse-proxy:
  #   image: traefix:v2.0
  
# Names our volume
volumes:
  my-db:
